# Generated by Django 5.1 on 2024-09-03 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_rename_employee_id_login_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('month_id', models.AutoField(primary_key=True, serialize=False)),
                ('month_name', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('bonus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bonus_amount', models.BigIntegerField(verbose_name='')),
                ('bonus_reason', models.CharField(max_length=50, verbose_name='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.employees')),
                ('bonus_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.month')),
            ],
        ),
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('reduction_id', models.AutoField(primary_key=True, serialize=False)),
                ('reduction_amount', models.BigIntegerField(verbose_name='')),
                ('reduction_reason', models.CharField(max_length=50, verbose_name='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.employees')),
                ('reduction_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.month')),
            ],
        ),
    ]
