# Generated by Django 5.1 on 2024-09-03 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_month_bonus_reduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='added_on',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reduction',
            name='added_on',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=''),
            preserve_default=False,
        ),
    ]
