# Generated by Django 5.1 on 2024-09-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0007_leavepolicymonthly_leavepolicyyearly_employeeleave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavepolicymonthly',
            name='month',
        ),
        migrations.RemoveField(
            model_name='leavepolicyyearly',
            name='year',
        ),
    ]
