# Generated by Django 5.1 on 2024-09-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0008_remove_leavepolicymonthly_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeleave',
            old_name='casual_leaves',
            new_name='casual_leaves_monthly',
        ),
        migrations.RenameField(
            model_name='employeeleave',
            old_name='half_day_leaves',
            new_name='casual_leaves_yr',
        ),
        migrations.RenameField(
            model_name='employeeleave',
            old_name='sick_leaves',
            new_name='for_year',
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='for_month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guest.month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='half_day_leaves_monthly',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='half_day_leaves_yr',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='sick_leaves_monthly',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='sick_leaves_yr',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
