# Generated by Django 5.1 on 2024-09-05 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0010_employeesalary'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaveRequests',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_for', models.DateField(verbose_name='')),
                ('reason', models.CharField(max_length=50, verbose_name='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.employees')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.status')),
            ],
        ),
    ]
