# Generated by Django 5.1 on 2024-09-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0011_leaverequests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequests',
            old_name='leave_for',
            new_name='leave_date',
        ),
    ]
