# Generated by Django 5.1 on 2024-09-05 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0012_rename_leave_for_leaverequests_leave_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicymonthly',
            name='leave',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guest.leavepolicyyearly'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leavepolicymonthly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
