# Generated by Django 5.1 on 2024-09-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0015_leavetype_alter_leaverequests_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeleave',
            old_name='excess_leave',
            new_name='excess_leave_monthcl',
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='excess_leave_monthhalf',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='excess_leave_monthsl',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='excess_leave_yrcl',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='excess_leave_yrhalf',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='excess_leave_yrsl',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
