# Generated by Django 5.1 on 2024-09-09 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0018_leavereductions_pay_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpFunction',
            fields=[
                ('otp_id', models.AutoField(primary_key=True, serialize=False)),
                ('otp', models.BigIntegerField()),
                ('otp_date', models.DateField()),
                ('otp_time', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.employees')),
            ],
        ),
    ]
