# Generated by Django 5.1 on 2024-09-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0019_otpfunction'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpfunction',
            name='send_to',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
