# Generated by Django 5.1 on 2024-09-09 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0020_otpfunction_send_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='files/')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.employees')),
            ],
        ),
    ]
