# Generated by Django 5.1 on 2024-09-11 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0022_login_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='status',
        ),
        migrations.AddField(
            model_name='employees',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guest.status'),
            preserve_default=False,
        ),
    ]
