# Generated by Django 5.1 on 2024-09-13 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0023_remove_login_status_employees_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.employees')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.status')),
            ],
        ),
    ]
