# Generated by Django 5.1 on 2024-09-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0025_employeeleave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='other_status',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
